name: Add to Project Board
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  repository-projects: write
  issues: write
  pull-requests: write

jobs:
  add-to-project:
    name: Add to Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/victorgmrqs/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
